# Generated by Django 5.2.1 on 2025-05-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_list', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='images\\default.jpg', upload_to='images/'),
        ),
    ]
